module std_srvs { module srv { 
 
struct Trigger_Request { 
    // a trigger for live singal
    boolean dummy; 
}; 

struct Trigger_Response { 
    // response
    boolean success; 
    string message; 
};

}; };
