# joy_stick_map
# lb_rb: "Default"
# lt_rt: "SecurityProtection"
# lb_a: "JointStand"
# lb_b: :PdStand"

# rb_a: "UserController_A"
# rb_b: "UserController_B"
# rb_y: "UserController_C"
# rb_x: "UserController_D"
# lb_x: "UserController_E"
# lb_y: "UserController_F"

# fsm states
Fsm:
  UserController_A: 
    allow_upper_body_override: false
    SimpleLocoTask:
        period: 0.02
        cup_priority: 1

  UserController_B: 
    allow_upper_body_override: false
    MoveJointTask:
        period: 0.1
        cup_priority: 1
     
  UserController_C: 
    allow_upper_body_override: false
    DdsCommTask:
        period: 0.1
        cup_priority: 1