module fourier_msgs { module msg { 
/** \brief time stamp message */
struct Time{
    int32 sec;
    uint32 nanosec;
};
/** \brief group control cmd message */
struct GroupCmd {
    string group_name;
    sequence<double> position; 
};

/** \brief teleoperation cmd message */
struct TeleoperationCmd {
    Time stamp;
    sequence<GroupCmd> groups_cmd;
};
}; };
